name: socialdemo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # State Management
  get: ^4.6.6

  # Internet Connectivity
  connectivity_plus: ^6.1.3

  # Local Storage
  shared_preferences: ^2.2.3

  # Firebase (commented out for now)
  # firebase_core: 1.2.0
  # firebase_auth: 1.2.0
  # firebase_messaging: ^10.0.0

  fluttertoast: ^8.2.8
  shimmer: ^3.0.0
  path_provider: ^2.1.3
  image_fade: ^0.6.2
  dio: ^5.5.0+1
  video_player: ^2.7.2
  share_plus: ^10.1.4
  visibility_detector: ^0.4.0
  carousel_slider: ^5.0.0
  sqflite: ^2.3.3+1

  http: ^1.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.0.0
  flutter_launcher_icons: ^0.14.3 # Add flutter_launcher_icons for generating launcher icons
  change_app_package_name: ^1.3.0

# Configuration for flutter_launcher_icons package
#flutter_icons:
#  android: true               # Generate icons for Android
#  ios: true                   # Generate icons for iOS
#  image_path: "assets/images/ic_launcher.png"  # Path to your app icon image
#  adaptive_icon_background: "#ffffff"      # Background color for adaptive icons on Android
##  adaptive_icon_foreground: "assets/icons/app_icon_fg.png"  # (Optional) Foreground image for adaptive icons

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/

  # Fonts (optional)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
